development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://ubsiqucwryuekz:e21e27ecb7fa00e5c9d338651c04c309fbe2e322353b00d655a90ee562fa4355@ec2-54-83-194-208.compute-1.amazonaws.com:5432/ddv7kfn5d79ugt
